# Generated by Django 3.0.7 on 2020-07-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='servings',
        ),
        migrations.CreateModel(
            name='ServingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.CharField(max_length=100)),
                ('servings', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servingTimes', to='recipe_app.Recipe')),
            ],
        ),
    ]
