# Generated by Django 3.0.7 on 2020-07-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20200706_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
